version: '3.8'

services:
  api:
    build: .
    ports:
      - "3305:3305"
    environment:
      - PORT=3305
      - DATABASE_URL=file:./prisma/dev.db
      - REDIS_URL=redis://cache:6379
      - HELIUS_API_KEY=${HELIUS_API_KEY}
      - POLL_MS=2000
    volumes:
      - dbdata:/app/prisma
    depends_on:
      - cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3305/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  cache:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  dbdata:
  redis_data: